# Generated by Django 4.0.4 on 2022-05-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paybylink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=2000000000)),
                ('description', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=2000000000)),
                ('description', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paybylink')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=2000000000)),
                ('description', models.CharField(max_length=200)),
                ('cardholder_name', models.CharField(max_length=20)),
                ('cardholder_surname', models.CharField(max_length=20)),
                ('card_number', models.IntegerField(max_length=16)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paybylink')),
            ],
        ),
    ]
