# Generated by Django 4.0.4 on 2022-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybylink',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLARS'), ('EU', 'EURO'), ('GBR', 'STERLING'), ('PLN', 'ZLOTY')], max_length=10),
        ),
    ]
