# Generated by Django 4.0.4 on 2022-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paybylink_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybylink',
            name='currency',
            field=models.CharField(choices=[('DOLLARS', 'USD'), ('EURO', 'EU'), ('STERLING', 'GBR'), ('ZLOTY', 'PLN')], max_length=10),
        ),
    ]
