# Generated by Django 4.0.4 on 2022-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_card_link_remove_dp_link_alter_card_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.ManyToManyField(blank=True, to='api.paybylink'),
        ),
        migrations.AddField(
            model_name='dp',
            name='link',
            field=models.ManyToManyField(blank=True, to='api.paybylink'),
        ),
    ]
